{
 "title": "dash-forum-api",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"},instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API USE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HEAP USED",
   "type": "gauge",
   "description": "memória heap utilizada",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"heap\"})*100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "CPU UTILIZATION",
   "type": "timeseries",
   "description": "utilização de cpu",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "NON-HEAP USED",
   "type": "gauge",
   "description": "MEMÓRIA NON-HEAP UTILIZADA",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"nonheap\"})*100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "LOAD AVERAGE",
   "type": "timeseries",
   "description": "Média de uso de CPU",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "Load Average[1m]"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  { "title": "BASIC API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "UPTIME",
   "type": "stat",
   "description": "API uptime",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}"
    }
   ]
  },
  {
   "title": "USERS LOGGED",
   "type": "stat",
   "description": "usuarios logados no ultimo minuto",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_success_total[1m])"
    }
   ]
  },
  {
   "title": "JDBC POOL",
   "type": "stat",
   "description": "pool de conexões jdbc",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}"
    }
   ]
  },
  {
   "title": "CONNECTION STATE",
   "type": "timeseries",
   "description": "estado das conexoes com o banco de dados",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "START TIME",
   "type": "stat",
   "description": "Hora da inicialização da api",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"} * 1000"
    }
   ]
  },
  {
   "title": "AUTH ERRORS",
   "type": "stat",
   "description": "erros de login no ultimo 1minuto",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(auth_user_error_total[1m])"
    }
   ]
  },
  {
   "title": "DB CONNECTION TIMEOUT",
   "type": "stat",
   "description": "conexoes com o banco de dados em timeout",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\",instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}[1m])"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOGS",
   "type": "timeseries",
   "description": "Warn e errors logados nos ultimos 5 minutos",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"warn\"}[5m]))",
     "legendFormat": "warn"
    },
    {
     "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"error\"}[5m]))",
     "legendFormat": "error"
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "TOTAL REQUESTS",
   "type": "stat",
   "description": "numero de requisições no ultimo minuto",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "numero de erros 500 no ultimo minuto",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))"
    }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "description": "latência média por minuto",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "description": "taxa de erros nos ultimos 5 minutos",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "tempo de resposta no ultimo minuto",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {}
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "description": "NUMERO DE REQUISICOES POR ENDPOINT NO ULTIMO MINUTO",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos\"}[1m]))",
     "legendFormat": "/topicos"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos/{id}\"}[1m]))",
     "legendFormat": "/topicos/{id}"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/auth\"}[1m]))",
     "legendFormat": "/auth"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "description": "duração media de requisições no ultimo minuto",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "MAX REQUEST DURATION",
   "type": "timeseries",
   "description": "duração maxima de uma requisição",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  }
 ]
}